routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\User;
use App\Product;
use App\Order;
use Illuminate\Support\Facades\Auth;

//  Auth::routes() is a helper class that helps you generate all the routes required for user authentication.
Auth::routes();

Route::get('/welcome', function () {
    return view('welcome');
});


// Route::get('/admin', function(){
// 	return view('admin.dashboard');
// });


// Profile
Route::get('/profile/{id}', 'UserController@profile');

Route::get('/add_profile', 'UserController@addprofile');

Route::post('/add_profile', 'UserController@add_profile');

Route::get('/update_profile/{id}', 'UserController@updateprofile');

Route::patch('/update_profile/{id}', 'UserController@update_profile');

Route::get('edit/{user}',  ['as' => 'edit', 'uses' => 'UserController@edit']);
Route::patch('edit/{user}/update',  ['as' => 'update', 'uses' => 'UserController@update']);
Route::post('edit/{user}', 'UserController@update_image');

// Route::get('edit/{user}', 'UserController@show')->middleware('auth')->name('edit/{user}.show');
// Route::post('edit/{user}', 'UserController@update')->middleware('auth')->name('edit/{user}.update');

// Route::get('/userviews/{profile}', 'UserController@profile')
// ->name('userviews.profile')->middleware('auth')->middleware('can:update_profile,profile');
// Route::put('/userviews/{profile}/update','UserController@update_profile')
// ->name('userviews.update_profile')->middleware('auth')->middleware('can:update_profile,profile');

// Route::resource('/users', 'UserController')->except('show')->middleware('auth')->middleware('admin');

// Resource method is used to create multiple routes for the ProductController & OrderController.
Route::resource('product','ProductController');
Route::resource('orders', 'OrderController')->except(['store', 'edit', 'update', 'destroy']);

// Getting the HomeController -> index function
Route::get('/', 'HomeController@index')->name('home');

// Getting the OrderController -> show function
Route::get('/order/{id}', 'OrderController@show');

// Getting OrderController -> index function
Route::get('/restaurant/{id}/orders', 'OrderController@index');

// Getting RestaurantController -> show function
Route::get('/restaurant/{id}', 'RestaurantController@show');

// Getting ProductController -> create function -> creating new product.
Route::get('/newproduct','ProductController@create');

// Getting RestaurantController -> stats function -> Used to display restaurant statistics such as (total amount).
Route::get('/restaurant/{id}/stats', 'RestaurantController@stats');


// Posting all Orders from the OrderController store function.
Route::post('orders', 'OrderController@store')->name('OrderController.store');

// About
Route::get('about', function() {
    return view('pages.about');
});

// Cart CRUD
Route::post('/addtocart/{id}', 'ProductController@addToCart');
Route::get('/showcart', 'ProductController@showCart');

// Delete Product
Route::delete('/removeproduct/{id}', "ProductController@removeProduct");

//  Empty Cart
Route::get('/clearcart', "ProductController@emptyCart");

// Checkout
Route::get('/checkout', "OrderController@checkout");

// Orders
// Route::get('/showorders', "OrderController@showOrders");

// Orders
Route::get('/history', "OrderController@showHistory");


// FEEDBACK & REPLIES
Route::resource('/feedback','FeedbackController');
Route::resource('/feedback_replies','FeedbackReplyController');
Route::post('/feedback_replies/ajaxDelete','FeedbackReply@ajaxDelete');

resources/views/addprofile.blade.php
@extends('layouts.app2')
@section('content')




<h1 class="text-center">Profile</h1>

	<div class="col-lg-8 offset-lg-2">
		<form action="/add_profile" method="POST" class="form-group">
			@csrf
			
			<div class="my-1">
				<label for="phone">Phone number</label>
				<input type="number" name="phone" class="form-control">
			</div>
			<div class="my-1">
				<label for="hours">Hours</label>
				<input type="hours" name="hours" class="form-control">
			</div>
			<div class="my-1">
				<label for="description">Description</label>
				<textarea name="description" class="form-control" rows="5"></textarea>
			</div>
			<div class="text-center">
				<button class="btn btn-info my-3">Add Profile</button>
			</div>
		</form>
	</div>

@endsection

resources/views/edit.blade.php
@extends('layouts.app2')
@section('content')


{{-- @if(Session::has("message"))
    <h4 class="alert alert-success text-align" role="alert">{{ Session::get('message') }}</h4>
@endif --}}

<link href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">

<body class="bg-gray-100" style="background-image: url(https://images.unsplash.com/photo-1496412705862-e0088f16f791?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80); background-attachment: fixed; opacity: 0.95;">

    <div class="bg-grey-lighter my-12 flex flex-col">
        <div class="container max-w-2xl mx-auto flex-1 flex flex-col items-center justify-center px-6">
            <div class="bg-white px-6 py-4 rounded shadow-md text-black w-full">
                <h1 class="mb-6 text-lg text-gray-900 font-thin flex justify-center items-center">Account Settings</h1>
                
                <form method="POST" action="{{route('update', $user)}}" enctype="multipart/form-data">
                @csrf
                 {{ method_field('patch') }}

                <fieldset class="m-2">
                    <div class="form-group row">
                        <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('Name') }}</label>
                        <div class="col-md-8">
                            <input id="name" type="name" value="{{ $user->name }}" class="form-control" name="name">
                        </div>
                    </div>
                </fieldset>

                <fieldset class="m-2">              
                    <div class="row justify-content-center mt-2 mb-4">
                        <div class="col-md-10">
                            <input type="file" class="form-control-file" name="image" id="imageFile" aria-describedby="fileHelp">
                            <small id="fileHelp" class="form-text text-muted">Please upload a valid image file. Size of image should not be more than 2MB.</small>
                        </div>  
                    </div>
                </fieldset>
                
                <fieldset class="m-2">
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label text-md-right" for="email">Email address</label>
                        <div class="col-md-8">                           
                            <input type="email" name="email" class="form-control" value="{{ $user->email }}" id="email">
                        </div>
                    </div>
                </fieldset>

                <fieldset class="m-2">
                    <div class="form-group row">
                        <label for="password" class="col-md-3 col-form-label text-md-right">{{ __('Password') }}</label>
                        <div class="col-md-8">
                            <input id="password" type="password" class="form-control" placeholder="Enter password" name="password">
                        </div>
                    </div>
                </fieldset>

                <fieldset class="m-2">
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label text-md-right" for="password">Confirm Password</label>
                        <div class="col-md-8"> 
                            <input type="password" placeholder="Confirm password" class="form-control" type="password" name="password_confirmation" id="password">
                        </div>
                    </div>
                </fieldset>

                <div class="form-group row mb-1">
                    <div class="col-md-8 offset-md-4">
                        <button type="submit" class="bg-green-600 hover:bg-green-800 text-white font-bold py-3 px-4 rounded">
                                    {{ __('Save Changes') }}
                        </button>
                    </div>
                </div>
                
                </form>

            </div>
        </div>
    </div>

{{-- <form method="post" action="{{route('update', $user)}}" enctype="multipart/form-data">
    @csrf
    {{ method_field('patch') }}
    <h3>Edit Profile</h3>

<div class="profile-header-container">
                <div class="profile-header-img">
                    
                    <div class="rank-label-container">
                        <span class="label label-default rank-label">{{$user->name}}</span>
                    </div>
                </div>
            </div>

        </div>
        <div class="row justify-content-center"> --}}
           {{--  <form action="{{ url('edit/{user}') }}" method="post" enctype="multipart/form-data">
                @csrf --}}
                {{-- <div class="form-group">
                    <input type="file" class="form-control-file" name="image" id="imageFile" aria-describedby="fileHelp">
                    <small id="fileHelp" class="form-text text-muted">Please upload a valid image file. Size of image should not be more than 2MB.</small>
                </div> --}}
                {{-- <button type="submit" class="btn btn-primary">Submit</button> --}}
            {{-- </form> --}}
        {{-- </div> --}}
    {{-- </div> --}}


@endsection

resources/views/feedback.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form id="feedback-form" method="post" action="{{ route('feedback.store') }}" >
                        {{ csrf_field() }}
                        <input type="hidden" name="user_id" value="{{ Auth::user()->id }}" >
                        <div class="row" style="padding: 10px;">
                            <div class="form-group">
                                <textarea class="form-control" name="feedback" placeholder="Write something from your heart..!"></textarea>
                            </div>
                        </div>
                        <div class="row" style="padding: 0 10px 0 10px;">
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary btn-lg" style="width: 100%" name="submit">
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>

    <div class="row">
         <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">feedback</div>

                <div class="panel-body feedback-container" >
                    
                    @foreach($feedbacks as $feedback)
                        <div class="well">
                            <i><b> {{ $feedback->name }} </b></i>&nbsp;&nbsp;
                            <span> {{ $feedback->feedback }} </span>
                            <div style="margin-left:10px;">
                                <a style="cursor: pointer;" cid="{{ $feedback->id }}" name_a="{{ Auth::user()->name }}" token="{{ csrf_token() }}" class="feedback_reply">feedback_reply</a>&nbsp;
                                <a style="cursor: pointer;"  class="delete-feedback" token="{{ csrf_token() }}" feedback-did="{{ $feedback->id }}" >Delete</a>
                                <div class="feedback_reply-form">
                                    
                                    <!-- Dynamic feedback_reply form -->
                                    
                                </div>
                                @foreach($feedback->feedback_replies as $rep)
                                     @if($feedback->id === $rep->feedback_id)
                                        <div class="well">
                                            <i><b> {{ $rep->name }} </b></i>&nbsp;&nbsp;
                                            <span> {{ $rep->feedback_reply }} </span>
                                            <div style="margin-left:10px;">
                                                <a rname="{{ Auth::user()->name }}" rid="{{ $feedback->id }}" style="cursor: pointer;" class="feedback_reply-to-feedback_reply" token="{{ csrf_token() }}">feedback_reply</a>&nbsp;<a did="{{ $rep->id }}" class="delete-feedback_reply" token="{{ csrf_token() }}" >Delete</a>
                                            </div>
                                            <div class="feedback_reply-to-feedback_reply-form">
                                    
                                                <!-- Dynamic feedback_reply form -->
                                                
                                            </div>
                                            
                                        </div>
                                    @endif 
                                @endforeach
                                
                            </div>
                        </div>
                    @endforeach

                </div>
            </div>
        </div>
    </div>

   

</div>
@endsection

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="{{ asset('/js/main.js') }}">
  
</script>

resources/views/home.blade.php
@extends('layouts.app2')

@section('title')
    HomePage
@endsection

@section('content')

<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">

        <title>FeedBack</title>

    </head>
    <body class="font-sans">


        <div class="max-w-5xl mx-auto p-8 py-20 flex justify-start items-center">
            <div class="flex-1">
                <h1 class="font-display-italic font-extrabold text-5xl md:text-6xl italic leading-none mb-6">Accelerate Good.</h1>
                <p class="leading-loose max-w-xl">Good food belongs to people, not landfills. Scroll below to browse food options.</p>
            </div>
            <div class="hidden md:block w-56">
                <a href="{{url("/welcome")}}" class="ml-12 bg-yellow-400 py-6 px-12">Enter</a>
            </div>
        </div>

<div class="carousel relative shadow-2xl bg-white">
    <div class="carousel-inner relative overflow-hidden w-full">

      <!--Slide 1-->
        <input class="carousel-open" type="radio" id="carousel-1" name="carousel" aria-hidden="true" hidden="" checked="checked">
        <div class="carousel-item absolute opacity-0">
            <img src="https://images.unsplash.com/photo-1503847752244-32e931070a43?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1586&q=80" style="height: 50vh;" class="w-full object-cover block" />
        </div>

        <label for="carousel-3" class="prev control-1 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
        <label for="carousel-2" class="next control-1 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label>
        
        <!--Slide 2-->
        <input class="carousel-open" type="radio" id="carousel-2" name="carousel" aria-hidden="true" hidden="">
        <div class="carousel-item absolute opacity-0">
            <img src="https://images.unsplash.com/photo-1489710020360-66e504159b43?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1651&q=80" style="height: 50vh;" class="w-full object-cover block" />
        </div>
        <label for="carousel-1" class="prev control-2 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
        <label for="carousel-3" class="next control-2 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label> 
        
        <!--Slide 3-->
        <input class="carousel-open" type="radio" id="carousel-3" name="carousel" aria-hidden="true" hidden="">
        <div class="carousel-item absolute opacity-0">
            <img src="https://images.unsplash.com/flagged/photo-1570088782323-e49798c279f8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1647&q=80" style="height: 50vh;" class="h-64 w-full object-cover block" />
        </div>
        <label for="carousel-2" class="prev control-3 w-10 h-10 ml-2 md:ml-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 left-0 my-auto">‹</label>
        <label for="carousel-1" class="next control-3 w-10 h-10 mr-2 md:mr-10 absolute cursor-pointer hidden text-3xl font-bold text-black hover:text-white rounded-full bg-white hover:bg-blue-700 leading-tight text-center z-10 inset-y-0 right-0 my-auto">›</label>

        <!-- Add additional indicators for each slide-->
        <ol class="carousel-indicators">
            <li class="inline-block mr-3">
                <label for="carousel-1" class="carousel-bullet cursor-pointer block text-4xl text-white hover:text-blue-700">•</label>
            </li>
            <li class="inline-block mr-3">
                <label for="carousel-2" class="carousel-bullet cursor-pointer block text-4xl text-white hover:text-blue-700">•</label>
            </li>
            <li class="inline-block mr-3">
                <label for="carousel-3" class="carousel-bullet cursor-pointer block text-4xl text-white hover:text-blue-700">•</label>
            </li>
        </ol>
        
    </div>
</div>

        {{-- <img src="https://images.unsplash.com/photo-1526016650454-68a6f488910a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1334&q=80" class="w-full h-64 object-cover" /> --}}

        <div class="max-w-5xl mx-auto pt-20 p-8 flex justify-start items-center">
            <h3 class="font-display-italic font-extrabold text-5xl md:text-6xl italic leading-none mb-12 max-w-xl">Restaurants.</h3>
        </div>

        <!-- Search Bar -->
     {{-- <div class="max-w-5xl mx-auto flex justify-start items-center">
        <form class="w-full max-w-sm" action="/search" method="POST">
            @csrf
            <div class="flex items-center input-group">
                <input class="border-2 border-gray-300 bg-white h-10 px-5 pr-16 rounded-lg text-sm focus:outline-none"
                  type="text" name="search" class="form-control" placeholder="Search">
                <div class="input-group-append">
                    <button class="flex-shrink-0 bg-purple-600 hover:bg-purple-800 text-white font-bold py-1 px-2 rounded" type="submit">Find Restaurant</button>
                </div>
            </div>
        </form>
    </div>
 --}}
 <div class="mainPageContent">

    <div class="container py-2">
        <div class="container mx-auto flex flex-wrap pb-20">
            @foreach ($restaurants ?? '' as $restaurant)
                <div class="w-full md:w-1/2 lg:w-1/3 px-6 mb-12">
                    <img class="w-full h-64 object-cover mb-6" src="{{asset($restaurant->image)}}" alt="Card image cap">      
                        <div>
                            <a href="{{ url('/restaurant/'.$restaurant->id) }}" class="text-2xl uppercase font-display font-extrabold tracking-widest mb-1 py-1 px-3 flex uppercase hover:bg-yellow-400">{{$restaurant->name}}</a>                           
                            <p class="font-display-italic italic text-l text-black-500 mb-4 px-3">{{$restaurant->address}}</p>
                        </div>
                </div>
            @endforeach
        </div>
    </div>

</div>

<script type="text/javascript">


    const filter = () => {
        // alert('hi');
        const catId = document.querySelector('#categoryFilter').value;
        // alert(catId);

        window.location.replace('/catalog/'+catId);
    }

    const addToCart = (id, productName) =>{
        console.log(productName)
        let quantity = document.querySelector("#quantity_"+id).value;
        alert(quantity + " of product " + productName + " has been added to cart");

        // let data = new FormData;

        // data.append("_token", "{{ csrf_token() }}");
        // data.append("quantity", quantity);

        fetch("/addtocart/"+id,{
            method: "POST",
            body: {
                "_token": {{csrf_token()}},
                "quantity": quantity
            }
        }).then(res=>res.text())
        .then(res=>console.log(res))
    }

</script>


        <div class="bg-black text-gray-500 text-center text-sm py-8">
            <p>Copyright &copy; 2020 feedback.</p>
        </div>

    </body>
</html>


@endsection

resources/views/profile.blade.php
@extends('layouts.app2')

@section('content')

@if(Session::has("message"))
    <h4>{{ Session::get('message') }}</h4>
@endif

@if(isset($profiles))

<link href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">

<h1 class="text-center">Profile</h1>
    <div class="container d-flex justify-content-center align-items-center flex-column">
        
            
            {{-- @foreach ($restaurants ?? '' as $restaurant)
            <div class="row justify-content-center">
                <img class="card-img-top" src="{{asset($restaurant->image)}}" alt="Card image cap">
            </div>
            @endforeach --}}
                        
            <div class="card-body text-center">
                <p>Phone Number: {{$profiles->phone}}</p>
            </div>
            <div class="card-body text-center">
                <p>Hours: {{$profiles->hours}}</p>
            </div>
            <div class="card-body text-center">
                <p>Description: {{$profiles->description}}</p>
            </div>
            <div class="text-center">
                <a href="/update_profile/{{$profiles->id}}" class="btn btn-info">Update Profile</a>
            </div>
        
    </div>
@else
        <div class="text-center">
                <a href="/add_profile" class="btn btn-info my-1">Add A Profile</a>
        </div>
@endif



{{-- <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8" style="padding-top:20px;">
            <div class="card">
                <div class="card-header"  style="text-align: center;">{{ __('Profile') }}</div>

                <div class="card-body">
                    
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                            <div class="col-md-6">
                                <input id="name" type="name" value="{{ $user->name }}" class="form-control" name="name">
                            </div>
                        </div>

                        <div class="row justify-content-center">
                            <img class="card-img-top" src="{{asset($restaurant->image)}}" alt="Card image cap">
                        </div>

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right" for="email">Email address:</label>
                            <div class="col-md-6">                           
                              <input type="email" name="email" class="form-control" value="{{ $user->email }}" id="email">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>
                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" placeholder="Enter password" name="password">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right" for="password">Confirm Password:</label>
                            <div class="col-md-6"> 
                              <input type="password" placeholder="Confirm password" class="form-control" type="password" name="password_confirmation" id="password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save Changes') }}
                                </button>

                            </div>
                        </div>
                   
                </div>
            </div>
        </div>
    </div>
</div> --}}

@endsection

resources/views/untitled.blade.php
 <div class="mainPageContent">
     

    <div class="container">

    <div class="row">
        <div class="col-xl" style="padding-top: 20px;">
            <div class="col-lg-5">
                <form class="p-3" action="/search" method="POST">
                    @csrf
                    <div class="input-group">
                        <input type="text" name="search" class="form-control" placeholder="Enter Restaurant Name">
                        <div class="input-group-append">
                            <button class="btn btn-info" type="submit">Find Restaurant</button>
                        </div>
                    </div>
                </form>
            </div>
            @foreach ($restaurants ?? '' as $restaurant)
            {{-- @dd($restaurant) --}}

                <div class="card" style="width: 18rem; display:inline-block; margin-left: 57px; margin-top: 20px;">
                    {{-- @dd(asset("/images/".$restaurant->image)) --}}
                    <img class="card-img-top" src="{{asset($restaurant->image)}}" alt="Card image cap" style="height: 300px;">
                    
                    <div class="card-body">
                        <h5 class="card-title"><a href="{{ url('/restaurant/'.$restaurant->id) }}">{{$restaurant->name}}</a></h5>
                        <p class="card-text">{{$restaurant->address}}</p>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>

<script type="text/javascript">


    const filter = () => {
        // alert('hi');
        const catId = document.querySelector('#categoryFilter').value;
        // alert(catId);

        window.location.replace('/catalog/'+catId);
    }

    const addToCart = (id, productName) =>{
        console.log(productName)
        let quantity = document.querySelector("#quantity_"+id).value;
        alert(quantity + " of product " + productName + " has been added to cart");

        // let data = new FormData;

        // data.append("_token", "{{ csrf_token() }}");
        // data.append("quantity", quantity);

        fetch("/addtocart/"+id,{
            method: "POST",
            body: {
                "_token": {{csrf_token()}},
                "quantity": quantity
            }
        }).then(res=>res.text())
        .then(res=>console.log(res))
    }

</script>

resources/views/updateprofile.blade.php
@extends('layouts.app')
@section('content')

<h1 class="text-center">Profile</h1>

	<div class="col-lg-8 offset-lg-2">
		<form action="/update_profile/{{$profile->id}}" method="POST" class="form-group">
			@csrf
			@method('PATCH')
			<div class="my-1">
				<label for="phone">Phone number</label>
				<input type="number" name="phone" class="form-control" value="{{$profile->phone}}">
			</div>
			<div class="my-1">
				<label for="hours">Hours</label>
				<input type="hours" name="hours" class="form-control" value="{{$profile->hours}}">
			</div>
			<div class="my-1">
				<label for="description">Description</label>
				<textarea name="description" class="form-control" rows="5">{{$profile->description}}</textarea>
			</div>
			<div class="text-center">
				<button class="btn btn-info my-3">Update Profile</button>
			</div>
		</form>
	</div>

@endsection